# Generated by Django 6.0.2 on 2026-03-05 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('home', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Select the service/product for this appointment', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
