# Generated by Django 6.0.2 on 2026-04-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('home', '0002_addons_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='addons',
            field=models.ManyToManyField(blank=True, to='home.addons'),
        ),
    ]
