# Generated by Django 6.0.2 on 2026-02-16 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='amount',
        ),
    ]
