# Generated by Django 6.0.2 on 2026-04-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
