# Generated by Django 6.0.2 on 2026-03-04 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_remove_gallery_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
