# Generated by Django 6.0.2 on 2026-04-09 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_service_remove_product_name_product_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='service',
        ),
    ]
