# Generated by Django 6.0.2 on 2026-04-09 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.service'),
            preserve_default=False,
        ),
    ]
