# Generated by Django 6.0.2 on 2026-04-09 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
