# Generated by Django 6.0.2 on 2026-04-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='addons',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Add on cost', max_digits=5),
        ),
        migrations.AlterField(
            model_name='addons',
            name='stripe_price_id',
            field=models.CharField(help_text='Stripe price ID (e.g., price_1234...)', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(help_text='Stripe price ID (e.g., price_1234...)', max_length=255),
        ),
    ]
