# Generated by Django 6.0.2 on 2026-04-10 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_addons_price_alter_addons_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='product',
        ),
        migrations.AddField(
            model_name='gallery',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.service'),
        ),
    ]
